DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS provider;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS permission;

CREATE TABLE patient (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  has_record BOOLEAN DEFAULT 0
);

CREATE TABLE provider (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  patient_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  symptoms TEXT NOT NULL,
  condition TEXT NOT NULL,
  treatment TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES provider (id),
  FOREIGN KEY (patient_id) REFERENCES patient (id)
);

CREATE TABLE permission (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  patient_id INTEGER NOT NULL,
  perm BOOLEAN DEFAULT 0,
  FOREIGN KEY (author_id) REFERENCES provider (id),
  FOREIGN KEY (patient_id) REFERENCES patient (id)
);